export default {
  appName: 'TaconKen',
  globalOk: 'OK',
  globalYes: 'Sim',
  globalCancel: 'Cancelar',
  lent: 'EMPRESTEI',
  borrowed: 'PEGUEI',
  newItemLent: 'Emprestei',
  newItemBorrowed: 'Peguei Emprestado',
  newItemLentTitle: 'Emprestei para',
  newItemBorrowedTitle: 'Peguei d@',
  newItemObjectTitle: 'Objeto',
  newItemSave: 'SALVAR',
  newItemSaveSuccess: 'Item salvo',
  itemDeleteSuccess: 'Item deletado',
  saveFailureMessage: 'Não foi possível salvar seu item, tente novamente mais tarde',
  deleteFailureMessage: 'Não foi possível deletar seu item, tente novamente mais tarde',
  emptyFieldMsg: 'Todos os campos devem ser preenchidos',
  emptyList: 'Nenhum item inserido clique no botão \'+\' para adicionar um novo item',
  deleteConfirmation: 'Deseja realmente deletar o item?',
};
